### ISSUE TITLE
Odd UI on "Build output folder" section.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#292] opened 2024-04-05 14:28 UTC
### Bug description

![Screenshot 2024-04-05 at 10 27 21 AM](https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/499ea4e4-68be-409c-86f6-1a7de7589238)

Unsure if this is an update upstream, but getting an odd looking UI input field for the output folder?

### Operating system

mac m1

### Version

next (development version)

### Additional context

Any ideas @benoitf @deboer-tim if this happens to be from the

**Comment by deboer-tim** [comment] 2024-04-10 14:43
This also affects the search bar on the homepage. I took a quick look, and it looks like the Input is the same as the PD component and the pd color variables are available in both cases, but the bootc webview fails to resolve the colors.

**Comment by cdrage** [comment] 2024-04-19 12:36
May be small, but I think IMHO we should have this fixed for 1.0.0

**Comment by benoitf** [comment] 2024-04-26 15:35
I didn't see the notification, I will investigate

**Comment by deboer-tim** [comment] 2024-04-26 15:42
Confirmed this is fixed by #396. Thank you Florent!

**Comment by benoitf** [comment] 2024-04-26 15:44
It looks the checkboxes are not rendering properly as well

**Comment by benoitf** [comment] 2024-04-26 15:46
so sorry I thought that this one was about the checkboxes not on the input field so yes this one is fixed sorry for the confusion

**Comment by deboer-tim** [comment] 2024-04-26 15:49
Yes, you opened #317 for checkboxes. :)

**Closed** 2024-04-26 17:05 UTC
Labels: kind/bug 🐞
