### ISSUE TITLE
Error encountered when trying to build a AMD64 bootc image

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop-extension-bootc#408] opened 2024-04-29 10:21 UTC
### Bug description

It seems that currently, on version 0.5.0 of the bootc extension trying to build an AMD64 image will always error out.

### Operating system

macOS

### Version

next (development version)

### Steps to reproduce

1. Have PD 1.10 installed.
2. Have bootc 0.5.0 version installed.
3. Have a container file with `FROM quay.io/centos-bootc/centos-bootc-dev:stream9`
4. Build the container file in AMD64 architecture.
5. Try to build a bootc image of any type using the image from previous point.
6. Error is thrown soon after starting.

[image-build-raw.log](https://github.com/containers/podman-desktop-extension-bootc/files/15147851/image-build.log)
[image-build-qcow.log](https://github.com/containers/podman-desktop-extension-bootc/files/15147859/image-build.log)

### Relevant log output

```shell
[0m[1mPipeline ostree-deployment: 947ed2e16a86c7353c7792854123c952676b6343d9442de7339ae2ecd7571548[0m
  root: a795fb92356ad1f6392b96f24bae3da27060b9e22cc6d83d6364060b35228277
[0m[1morg.osbuild.ostree.init-fs: 92162177b70dd30af4c236af83152da6b939285764091e7cd8c46094f834f47c[0m {}
  runner: org.osbuild.linux (org.osbuild.linux)
⏱  Duration: 7s

manifest - failed
bwrap: execvp /run/osbuild/runner/org.osbuild.linux: Exec format error
[0m[1m[31mFailed[0m
Build
⏱  Duration: 0s
2024/04/29 10:04:37 error: cannot run osbuild: running osbuild failed: exit status 1
Error: cannot run osbuild: running osbuild failed: exit status 1
```

**Comment by odockal** [comment] 2024-04-29 10:37
Here is mine output of a successful build of the image in Windows. I have used amd64 platform to build the containerfile and disc image.
[image-build.log](https://github.com/containers/podman-desktop-extension-bootc/files/15148065/image-build.log)

**Comment by deboer-tim** [comment] 2024-04-29 12:43
Could not reproduce on Mac 14.4.

**Comment by cdrage** [comment] 2024-04-29 12:47
@cbr7 This looks like it's pointing to an issue with the host. Particularly this was an issue with podman machine and qemu: https://github.com/osbuild/bootc-image-builder/pull/335

Could you post your podman version (particularly machine).

**Comment by cbr7** [comment] 2024-04-29 13:02
It seems that uninstalling  and then reinstalling podman fixed the problem, I've just been able to build AMD64 images.

**Comment by cdrage** [comment] 2024-05-31 12:34
Closing this as this is podman / podman machine upstream related due to qemu not being very stable on mac with building x86_64 images.

**Closed by cdrage** 2024-05-31 12:34 UTC
Labels: kind/bug 🐞
