### ISSUE TITLE
Support fetching builder container via label

### ISSUE THREAD

**Issue by cgwalters** [containers/podman-desktop-extension-bootc#389] opened 2024-04-25 16:00 UTC
### Is your enhancement related to a problem? Please describe

See https://github.com/CentOS/centos-bootc/pull/453/commits/44561ffb9b77c3023e062ee2c44656b752c473ef

It'd be good to parse that label and honor it going forward as it will allow different operating systems to reference different builder images.

### Describe the solution you'd like

Parse the label

**Comment by deboer-tim** [comment] 2024-04-25 17:52
Dupe of #238, closing.

FWIW, to me this is blocked until we know what is going to happen with https://github.com/osbuild/bootc-image-builder/issues/111, i.e. what is the story for versioning / multi-builder / cross-compatibility.

**Closed by deboer-tim** 2024-04-25 17:52 UTC
Labels: kind/enhancement ✨

**Comment by cgwalters** [comment] 2024-04-25 17:55
Ah yes sorry I thought we had a ticket here but I was searching for ones I filed.
