### ISSUE TITLE
looks like the search component is not matching what is in Podman Desktop

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop-extension-bootc#395] opened 2024-04-26 14:16 UTC
### Is your enhancement related to a problem? Please describe

there is a blue outline, the magnifying glass is with a gray background and the search field is with a darker background

![image](https://github.com/containers/podman-desktop-extension-bootc/assets/436777/6dde80ad-244f-47cc-bfd4-7707aeb8732f)

### Describe the solution you'd like

this is what I have for containers:
![image](https://github.com/containers/podman-desktop-extension-bootc/assets/436777/58f419f2-3542-40e5-88ec-35c1639c8b5e)

**Comment by deboer-tim** [comment] 2024-04-26 14:19
Duplicate of #292, the color variables are not working and haven't been able to figure it out yet.

**Closed by deboer-tim** 2024-04-26 14:19 UTC
Labels: kind/enhancement ✨

**Comment by benoitf** [comment] 2024-04-26 15:27
I believe it's two separate issues as Input component is coming from the 3rd party library

**Comment by deboer-tim** [comment] 2024-04-26 15:46
Search is just a variant of Input, and in both cases it was the variables not taking effect - anyway, your fix is solving both when I test.
